// Generated by CoffeeScript 1.4.0

/*
jQuery Gridly
Copyright 2013 Kevin Sylvestre
*/


(function() {
  "use strict";

  var $, Animation, Gridly,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  $ = jQuery;

  Animation = (function() {

    function Animation() {}

    Animation.transitions = {
      "webkitTransition": "webkitTransitionEnd",
      "mozTransition": "mozTransitionEnd",
      "msTransition": "msTransitionEnd",
      "oTransition": "oTransitionEnd",
      "transition": "transitionend"
    };

    Animation.transition = function($el) {
      var el, result, type, _ref;
      el = $el[0];
      _ref = this.transitions;
      for (type in _ref) {
        result = _ref[type];
        if (el.style[type] != null) {
          return result;
        }
      }
    };

    Animation.execute = function($el, callback) {
      var transition;
      transition = this.transition($el);
      if (transition != null) {
        return $el.one(transition, callback);
      } else {
        return callback();
      }
    };

    return Animation;

  })();

  Gridly = (function() {

    Gridly.settings = {
      base: 60,
      gutter: 20,
      columns: 12
    };

    Gridly.gridly = function($el, options) {
      if (options == null) {
        options = {};
      }
      return new Gridly($el, options);
    };

    function Gridly($el, settings) {
      if (settings == null) {
        settings = {};
      }
      this.layout = __bind(this.layout, this);

      this.$ = __bind(this.$, this);

      this.$el = $el;
      this.settings = $.extend({}, Gridly.settings, settings);
    }

    Gridly.prototype.$ = function(selector) {
      return this.$el.find(selector);
    };

    Gridly.prototype.grow = function() {
      return this.grid.push();
    };

    Gridly.prototype.layout = function() {
      var columns, i,
        _this = this;
      this.$el.offset();
      columns = (function() {
        var _i, _ref, _results;
        _results = [];
        for (i = _i = 0, _ref = this.settings.columns; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
          _results.push(0);
        }
        return _results;
      }).call(this);
      this.$('> *').each(function(index, element) {
        var $element, column, height, max, size, _i, _j, _ref, _ref1;
        $element = $(element);
        size = (($element.data('width') || $element.width()) + _this.settings.gutter) / (_this.settings.base + _this.settings.gutter);
        height = Infinity;
        column = 0;
        for (i = _i = 0, _ref = columns.length - size; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
          max = Math.max.apply(Math, columns.slice(i, i + size));
          if (max < height) {
            height = max;
            column = i;
          }
        }
        for (i = _j = column, _ref1 = column + size; column <= _ref1 ? _j < _ref1 : _j > _ref1; i = column <= _ref1 ? ++_j : --_j) {
          columns[i] = height + ($element.data('height') || $element.height()) + _this.settings.gutter;
        }
        return $element.css({
          position: 'absolute',
          left: column * (_this.settings.base + _this.settings.gutter),
          top: height
        });
      });
      return this.$el.css({
        height: Math.max.apply(Math, columns)
      });
    };

    return Gridly;

  })();

  $.fn.extend({
    gridly: function(option) {
      if (option == null) {
        option = {};
      }
      return this.each(function() {
        var $this, action, options;
        $this = $(this);
        options = $.extend({}, $.fn.gridly.defaults, typeof option === "object" && option);
        action = typeof option === "string" ? option : option.action;
        if (action == null) {
          action = "layout";
        }
        return Gridly.gridly($this, options)[action]();
      });
    }
  });

}).call(this);
